name: Common
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      is-snapshot:
        required: false
        type: boolean
        default: true
      change-log:
        required: false
        type: string

jobs:
  build-common:
    name: Build Common
    runs-on: ubuntu-latest
    environment: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
      -
        name: Build
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
        run: |
          ./gradlew clean shadowJar --info --stacktrace
          cp ./build/libs/*.jar ./
      -
        uses: actions/upload-artifact@v3
        with:
          name: I7MEUpdateMod-${{ inputs.type }}-${{ github.run_number }}.jar
          path: build/libs
      - 
        name: 🧧 Create GitHub Release
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-${{ github.run_number }}
          files: ${{github.workspace}}/I7MEUpdateMod-${{ inputs.type }}-${{ github.run_number }}.jar
          generate_release_notes: true