name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

jobs:
  build-pull-request:
    name: Build Pull Request
    uses: ./.github/workflows/common.yml
    with:
      type: PullRequest