name: Release
on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build Release
    uses: ./.github/workflows/common.yml
    with:
      type: Release
      is-snapshot: false
      change-log: ${{ github.event.release.body }}
    secrets: inherit